// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRXxJB3sDm2LIzb9D0y8Q3CFtRXAJMbg',
    appId: '1:790973599686:web:8267914a78c1ebe33eecc7',
    messagingSenderId: '790973599686',
    projectId: 'sport80-e6f93',
    authDomain: 'sport80-e6f93.firebaseapp.com',
    databaseURL: 'https://sport80-e6f93-default-rtdb.firebaseio.com',
    storageBucket: 'sport80-e6f93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoysC7y714HxaCMpG-hwkTuh0OKnWxbnE',
    appId: '1:790973599686:android:0074dc4999f86c613eecc7',
    messagingSenderId: '790973599686',
    projectId: 'sport80-e6f93',
    databaseURL: 'https://sport80-e6f93-default-rtdb.firebaseio.com',
    storageBucket: 'sport80-e6f93.appspot.com',
  );
}
